### ISSUE TITLE
input:active (and .active) should use better color

### ISSUE THREAD

**Issue by ghost** [mozilla/calculator#78]
Currently, `.active` class is using `#0f0f0f` for `background-color`. That setting is making app unusable outside since user is not able to clearly see what is happening on screen and what operation is active.

My proposal is to use something like `#008EAB`

![screen shot 2014-07-07 at 03 23 03](https://cloud.githubusercontent.com/assets/363870/3560292/0f8b5c08-0962-11e4-999b-81dbd206f0d2.png)

or `#4B780A`

![screen shot 2014-07-07 at 03 22 15](https://cloud.githubusercontent.com/assets/363870/3560291/0f83515c-0962-11e4-806a-1e6ceb501a9b.png)

Proposed colors are from [Mozilla Firefox OS color palette page](http://www.mozilla.org/en-US/styleguide/products/firefox-os/color/).

**Comment by joshua-s** [comment]
This was fixed by #90. Let's close it.
