### ISSUE TITLE
can't continue calculations after scientific notation displayed

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/calculator#94]
migrated from https://bugzilla.mozilla.org/show_bug.cgi?id=1177837

User-Agent: Mozilla/5.0 (Mobile; rv:41.0) Gecko/41.0 Firefox/41.0

Step 1: Enter 12345678, then the multiply operation.
Step 2: Enter 12345678, then equal
Step 3: Enter multiply then 3 then equal

Expected result: correct number in scientific notation

Actual result: nothing happens, the number 3 remains on-screen.

Note that entering multiply again seems to work fine.

**Comment by ianest** [comment]
Pull Request #100
